version: 0.2

phases:
  install:
    runtime-versions:
          commands:
           echo "Installing dependencies..."

  pre_build:
    commands:
            echo "Running pre-build steps..."
      
  build:
    commands:
           echo "Building the HTML project..."
     
      cp -r * $CODEBUILD_SRC_DIR/build/  

  post_build:
    commands:
      echo "Build completed successfully!"
           
artifacts:
  files:
    - '**/*'  
  discard-paths: yes  

